media:
  input: src/media
  output: src/media

content:
  - name: articles
    label: Articles
    path: src/content/articles
    type: collection
    view:
      fields: [ title, date, draft ]
      primary: title
    fields:
      - {name: title, label: Title, type: string }
      - {name: date, label: Date, type: date }
      - {name: description, label: Description, type: text, options: { maxlength: 160 }}
      - {name: draft, label: Draft, type: boolean, default: true }
      - {name: tags, label: Tags, type: select, options: { multiple: true, creatable: true} }
      - {name: socialimage, label: Social Image, type: image, options: {extensions: [jpg]}}
      - {name: body, label: Body, type: rich-text }

  - name: album-reviews
    label: Album Reviews
    path: src/content/album-reviews
    type: collection
    view:
      fields: [ title, date, draft ]
      primary: title
    fields:
      - {name: title, label: Title, type: string }
      - {name: date, label: Date, type: date }
      - {name: description, label: Description, type: text, options: { maxlength: 160 }}
      - {name: draft, label: Draft, type: boolean, default: true }
      - {name: tags, label: Tags, type: select, default: album review, options: { multiple: true, creatable: true} }
      - {name: reviewtype, label: Review Type, type: string, hidden: true, default: album }
      - {name: artist, label: Artist, type: string }
      - {name: album, label: Album, type: string }
      - {name: year, label: Release Year, type: string }
      - {name: runtime, label: Runtime, type: string }
      - {name: score, label: Score, type: string }
      - {name: socialimage, label: Social Image, type: image, options: {extensions: [jpg]}}
      - {name: image, label: Featured Image, type: image }
      - {name: body, label: Body, type: rich-text }

components:
  commonFields:
    label: Common Fields
    type: object
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: description
        label: Description
        type: text
        required: false
      - name: draft
        label: Draft
        type: boolean
        required: false
