media:
  input: src/media
  output: src/media
 
content:
  - name: album-reviews
    label: Album Reviews
    path: src/content/album-reviews
    type: collection
    view:
      fields: [ title ]
      primary: title
    
    fields:
      - name: common
        component: common

  - name: articles
    label: Articles
    path: src/content/articles
    type: collection
    view:
      fields: [ title ]
      primary: title
    fields:
      - name: common
        component: common
  - name: coffee
    label: Coffee Reviews
    path: src/content/coffee
    type: collection
    fields:
      - name: common
        component: common
  - name: mainstream
    label: Mainstream Sheep
    path: src/content/mainstream
    type: collection
    fields:
      - name: common
        component: common
  - name: movie-reviews
    label: Movie Reviews
    path: src/content/movie-reviews
    type: collection
    fields:
      - name: common
        component: common
  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    fields:
      - name: common
        component: common

components:
  common:
    label: Common post fields
    type: object
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: description
        label: Description
        type: text
        required: false
      - name: draft
        label: Draft
        type: boolean
        required: false
